language: node_js
node_js:
  - "10.12.0"
cache: yarn
script:
  - yarn run docs:build
  - echo 'developers.yggdrash.io' > docs/.vuepress/dist/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: master