language: node_js
node_js:
  - "10.12.0"
cache: yarn
script:
  - yarn run docs:build
  - cd docs/.vuepress/dist
  - echo 'developer.yggdrash.io' > CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master